version: '2'

services:
  cassandra:
    image: 'bitnami/cassandra:3'
    ports:
      - '7000:7000'
      - '9042:9042'
    volumes:
      - 'cassandra_data:/bitnami'
      - './init.sh:/docker-entrypoint-initdb.d/init.sh'
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra

  web:
    image: metavige/cassandra-web
    ports:
      - 3000:3000
    environment:
      - CASSANDRA_HOST=172.24.0.2
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra


volumes:
  cassandra_data:
    driver: local