version: '3.3'

services:

  postgres:
    image: postgres:11-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: 'pepa-linha'