CREATE USER user1 WITH PASSWORD 'user1';
CREATE DATABASE db1;
GRANT ALL PRIVILEGES ON DATABASE db1 TO user1;

CREATE USER user2 WITH PASSWORD 'user2';
CREATE DATABASE db2;
GRANT ALL PRIVILEGES ON DATABASE db2 TO user2;

CREATE USER user3 WITH PASSWORD 'user3';
CREATE DATABASE db3;
GRANT ALL PRIVILEGES ON DATABASE db3 TO user3;

CREATE USER user4 WITH PASSWORD 'user4';
CREATE DATABASE db4;
GRANT ALL PRIVILEGES ON DATABASE db4 TO user4;

CREATE USER user5 WITH PASSWORD 'user5';
CREATE DATABASE db5;
GRANT ALL PRIVILEGES ON DATABASE db5 TO user5;
